### PR TITLE
Completing buffer module, for #112

### PR DESCRIPTION
**Pull request by ILyoan**
Completing buffer module, for #112

* Refactoring JObjectWrap, moving jholder from JHandlerWrap.
* Renaming confusing member name 'jnative' to 'jobject'.
* Completing buffer module.
 * Buffer.isBuffer()
 * Buffer.prototype.equals()
 * Buffer.prototype.compare()
 * Buffer.prototype.copy()
 * Buffer.prototype.slice()
 * Buffer.prototype.toString()
* Revisit buffer tester.

IoT.js-DCO-1.0-Signed-off-by: Ilyong Cho ily.cho@samsung.com

### CODE REVIEW

**Comment by chunseoklee** [comment]
I'll make a new issue to support negative index in buf.slice.
Except this, LGTM.
Lets push.

**Comment by ILyoan** [comment]
@seanshpark Fixed typo
This PR modified `JObjectWrap` hence will conflict with PR #113.

**Comment by seanshpark** [comment]
@ILyoan , it's ok with the conflict, it can be resolved.

**Comment by ILyoan** [comment]
@chunseoklee Rebase on top of master.
Addressed #116.
r?

**Comment by chunseoklee** [comment]
LGTM lets push

**Comment by ILyoan** [comment]
merged

**Pull request closed without merging**
