### PR TITLE
Rename test_promise.js to test_iotjs_promise.js

### PR DESCRIPTION
**Pull request by galpeter**
As per #743 the test_promise.js name for the test
would expect that the iotjs would be built with
promise iotjs(!) module. However the promise is
not an iotjs feature but it is provided by the
underlying JS engine JerryScript. Thus the test
runner incorrectly returns the reason for skipping
the test, stating that is not supported by the
iotjs build but that is the incorrect message.

By renaming the testcase to test_iotjs_promise.js
the correct skip reason is displayed and will
make it easier in the future to enable the test case.

IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by glistening** [comment]
@galpeter I didn't recognized that the file name is related to test runner's running. The PR is good for me. However, at least for me, this PR's new name is counter-intuitive. Because it requires iotjs infix, although promise is JavaScript engine (jerryscript) 's feature, not iotjs's feature. Anyway, I think it would be better to make a document about test file naming rule. Could you make a document in doc/dev?

**Comment by glistening** [comment]
@galpeter I think #743 explanation is enough. We can use #743 for a new document for making test cases in developer guide. Also, we need to add comment for exceptional cases, that "_For tests that don't belong to any iotjs module, use iotjs infix._ " (although I still feel strange).

**Comment by galpeter** [comment]
We can introduce another "virtual" module name which is hardcoded into the testing system so it knows how to handle them. So if you have another idea instead of the 'iotjs' name we can change it. I picked the 'iotjs' as it is a must have module.

Should I add the doc into this PR or a separate one?

**Comment by glistening** [comment]
@galpeter `iotjs` infix is enough for me if the rule is documented explicitly. I found there is already [To write a testcase](https://github.com/Samsung/iotjs/blob/master/docs/help/Getting-Started.md#to-write-a-test-case) in Getting Started. Could you please add a bullet for testcase naming rule? Thank you.

**Comment by galpeter** [comment]
I've updated the PR with the requested documentation change.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
