### PR TITLE
add openwrt support

### PR DESCRIPTION
**Pull request by qdk0901**
Hi, I add this to openwrt running on mips soc, there are changes on libtuv and jerry, I will make pull request seperately.

### CODE REVIEW

**Comment by qdk0901** [comment]
sorry, see the last commit please, I merge the commits and add signed-off

**Comment by scriby** [comment]
I am very interested in running this on a openwrt mips soc as well. Thanks for doing all this work to make it possible!

**Comment by qdk0901** [comment]
@scriby 
The pull request on iotjs,jerry and libtuv seems can not be handled soon. 
I have pushed the code to github with all submodules updated to the latest version.
https://github.com/qdk0901/iotjs-openwrt.git

**Comment by scriby** [comment]
Dear maintainers,

I'm sure you are very busy! I would really appreciate it if you could take a look at this. Let me know if there's anything I can do to help.

Thanks!

**Comment by LaszloLango** [comment]
@qdk0901, please rebase you PR to the current master and squash the commits.

**Comment by LaszloLango** [comment]
@qdk0901, this PR is inactive for a long time, so we have to close it. Don't hesitate to reopen it if you'd like to continue.

**Pull request closed without merging**
