### PR TITLE
module: add __filename and __dirname

### PR DESCRIPTION
**Pull request by yorkie**
Add the `__filename` & `__dirname` to module file context.

### CODE REVIEW

**Comment by zherczeg** [comment]
Is this a non-standard extension?

**Comment by yorkie** [comment]
Nope, it's standard in Node.js, see https://nodejs.org/dist/latest-v9.x/docs/api/globals.html#globals_dirname

**Comment by glistening** [comment]
@yorkie I am not sure whether we should provide them in iotjs just because they exists in node.js. I would like to know the specific reason: Are you trying to reuse node.js module? Are you writing your own module that requires `__filename` or`__dirname`?

**Comment by yorkie** [comment]
@glistening there are Node.js modules which uses `__dirname`, and it should could be used directly in IoT.js!

**Comment by LaszloLango** [comment]
@yorkie what modules use `__dirname`? We have to consider the runtime memory usage. This change will increase the memory usage for every module, not just for those which use it. A few bytes does not matter in case of Nodejs. Our usecase is different. If some module really need this feature then we might consider a different approach even if it could be slower.

**Comment by yorkie** [comment]
In Node.js, developer uses `__dirname` in usual to search filename based on the current module file, could we finish the same function in IoT.js?

**Comment by yichoi** [comment]
Closing since I think above answer of @glistening quite enough for you.

**Pull request closed without merging**
