### PR TITLE
Removed 'iotjs_jval_destroy'

### PR DESCRIPTION
**Pull request by LaszloLango**
IoT.js-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by yichoi** [comment]
BTW, It is true that IoT.js is dependent with JerryScript however I am not sure that using ```jerry_release_value``` directly is good or not in the end. I am somewhat inclined to use ```iotjs_jval_destroy``` as a alias or definition of ```jerry_release_value```. Any challenges are welcomed :)

**Comment by zherczeg** [comment]
My thinking is using jerry functions directly simplify iotjs, so it is easier to understand for everybody. Perhaps the question is whether we want to add extra functionality for this function in the future. If this is unlikely, I would remove this one-liner.

**Comment by yichoi** [comment]
either way fine with me :)

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
