### PR TITLE
Rework on GPIO

### PR DESCRIPTION
**Pull request by ILyoan**
Rework on GPIO based on previous implementation.

* Reimplement gpio.js to meet GPIO API.
* Reimplement gpio module due to changes on gpio.js.
* Rename gpio module 'gpioctl' to 'gpio'.
* Rename 'device' directory to 'platform'
* Added GPIO implementation for linux generic.

### CODE REVIEW

**Comment by chunseoklee** [comment]
How about emitting 'write' event on write complete? 
IMHO, distinction among event owner might be an issue.

**Comment by ILyoan** [comment]
@chunseoklee It requires only simple work to adding 'write' event. 

Do you think providing that feature would make it easier to write GPIO program?
And what about 'read' event?

**Comment by chunseoklee** [comment]
Sure,  it would be nice since cb hell is pain.

**Comment by ILyoan** [comment]
@chunseoklee Then we need to review on GPIO API.

writePin has below prototype:
```
writePin(pinNumber: Number, value: Boolean, callback: Function(Error))
```
The callback function does not takes `pinNumber` and `value` since they are obvious.

If we decide to provide 'write' event, it would be like:
```
event: write (pinNumber: Number, value: Boolean) 
```

Are you OK with it?

**Comment by chunseoklee** [comment]
@ILyoan Yes. Agree with event wih pinnumber  to recognize who is in charge of an event.

**Comment by ILyoan** [comment]
@chunseoklee Opened issue to discuss about API 
# 217

**Comment by ILyoan** [comment]
@chunseoklee Applied emitting 'writePin' and 'readPin' event after `writePin()` and `readPin()` operation respectively. callback parameter for `readPin()` become optional.

**Comment by chunseoklee** [comment]
LGTM

**Pull request closed without merging**
