### PR TITLE
update docs/Build-for-NuttX-(new).md with latest wiki-page

### PR DESCRIPTION
**Pull request by haesik**
it's a updating of docs/Build-for-NuttX-(new).md and 
i have change the cmake/config.cmake sample to fix the wchar_t issue

### CODE REVIEW

**Comment by yichoi** [comment]
related with issue #378

**Comment by yichoi** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Comment by LaszloLango** [comment]
DCO is missing from the commit message!

**Comment by LaszloLango** [comment]
@haesik, please add your Sign-off to the end of the commit message. For details check https://github.com/Samsung/iotjs/wiki/IoT.js-Developer's-Certificate-of-Origin-1.0

**Comment by yichoi** [comment]
DCO added. LGTM

**Comment by LaszloLango** [comment]
@haesik, thank you for the update. LGTM
@yichoi, you can land it now :)

**Pull request merged**
