### PR TITLE
ADC implemented and tested for TizenRT port.

### PR DESCRIPTION
**Pull request by pmarcinkiew**
1. Pin field enabled for TizenRT in iotjs_module_adc.
2. New binding for TizenRT introduced based on sensorboard demo from
   TizenRT.

### CODE REVIEW

**Comment by pmarcinkiew** [comment]
This change will compile with version of TizenRT from pull request.

https://github.com/Samsung/TizenRT/pull/198

**Comment by yichoi** [comment]
https://travis-ci.org/Samsung/iotjs/jobs/242920513

**Comment by yichoi** [comment]
@pmarcinkiew BTW, please add your test result on real target like https://samsung.github.io/iotjs-test-results/

**Comment by pmarcinkiew** [comment]
We will need some more time to first create stable Travis build and later enable ADC. The TizenRT was just very deeply changed and my compilation scripts fail to integrate with it. I will recreate this PR again after these pre-requirements will be met.

**Pull request closed without merging**
