### PR TITLE
Complete Darwin support

### PR DESCRIPTION
**Pull request by akosthekiss**
Update build system to handle Darwin platforms properly, and remove
"Darwin not ready" message.

IoT.js-DCO-1.0-Signed-off-by: Akos Kiss akiss@inf.u-szeged.hu

### CODE REVIEW

**Comment by LaszloLango** [comment]
Could you also add a travis job for it in this PR?

**Comment by akosthekiss** [comment]
Will do, but it seems it needs some more massaging.

**Comment by akosthekiss** [comment]
tools/build.py worked OK with just some changes here and there in 2 files, but to make precommit.py happy, some 11 more files had to be changed/added. now, the PR is updated but the changes are still scattered across 4 commits. if the reviews are positive, I can squash them into a single commit (or it can be done via the web interface as well by using squash-and-merge).

**Comment by akosthekiss** [comment]
After the LGTMs, master moved forward and broke the PR. I had to adjust the code further to get everything working again. As part of this, I had to change the dns module (iotjs_module_dns.c). @wateret could you please check that I got things right there (the changed part seems to have been authored by you)

**Comment by LaszloLango** [comment]
still LGTM from my side

**Pull request merged**
