### PR TITLE
Rework the build.py script

### PR DESCRIPTION
**Pull request by galpeter**
Main point of rework:
* Added help description for options
* Added default value for options
* Removed global option variables
* Extracted common parts:
   * Make execution
   * Binary/library copies
* If no-snapshot is specified then building host jerry is disabled

IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by galpeter** [comment]
The Travis error are caused (mostly) by the help messages as they don't fit into 80 long lines. Could we relax the requirement to 100 long lines perhaps? Or should I rework them to 80 long lines?

**Comment by yichoi** [comment]
Please rebase it to the master

**Comment by yichoi** [comment]
Please fit it to 80 long lines

**Comment by galpeter** [comment]
@yichoi Now everything is under 80 lines and the PR was rebased.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
