### PR TITLE
Adding details on how to configure interfaces on the Raspberry Pi Zer…

### PR DESCRIPTION
**Pull request by nherriot**
This adds details for people using the Raspberry Pi Zero on how to configure I2C, SPI and Serial interfaces which is slightly different to the ones documented.

It also adds a missing link to the 'raspberry pi2 with Tizen document' which is on the system, but you can't get to it from the 'getting started' page.

### CODE REVIEW

**Comment by galpeter** [comment]
There is a missing DCO signed off for the commit, please update (see: https://github.com/Samsung/iotjs/wiki/IoT.js-Developer's-Certificate-of-Origin-1.0).
Otherwise LGTM

**Comment by nherriot** [comment]
Hi Samsung guys. I've added the sign-off now. Hope this is good.

Kind regards, Nicholas.

**Comment by yichoi** [comment]
@nherriot Please make one single commit

**Comment by glistening** [comment]
@nherriot Please use IoT.js sign-off form. See https://github.com/Samsung/iotjs/pull/1416#issuecomment-357969418.

**Comment by nherriot** [comment]
Sign off form is now complete in my ./git/hook dir.

Kind regards, Nicholas

**Comment by yichoi** [comment]
@nherriot still you have two commit in one PR.

**Comment by glistening** [comment]
@nherriot Travis still complains about your sign-off form. Please see the travis error.

Signed-off-by message is incorrect. The following line should be at the end of the 6d64bb1 commit's message: 'IoT.js-DCO-1.0-Signed-off-by: nicholas.herriot nicholas.herriot@gmail.com'.

**Comment by nherriot** [comment]
@glistening you are going to have to give me more information on the hoops I have to jump through to get the patch approved by the travis build. Did you look at the commit log? (e.g. /> git log )
When I look at my log it says:

Date: Fri Jan 19 ..........
        Small change with new sign-off key
        **Signed-off-by: nicholas.herriot <nicholas.herriot@gmail.com>**

However the travis build says:
     Signed-off-by message is incorrect. The following line should be at the end of the 6d64bb1 commit's message: 'IoT.js-DCO-1.0-Signed-off-by: nicholas.herriot nicholas.herriot@gmail.com'. 

Please let me know what is it you want me to do in clear precise English and if possible a link to an example. Do you want me to submit another commit with a simple change and add the line in my commit message manually:
'IoT.js-DCO-1.0-Signed-off-by: nicholas.herriot nicholas.herriot@gmail.com'.  ?

This is the error message I'm looking at:
     https://travis-ci.org/Samsung/iotjs/jobs/330775810

You can also contact me at n.herriot@samsung.com - I happen to be the IoT Technology Manager in the R&D centre in West London.  Perhaps I can also help you improve the guides to help developers navigate the process in the coming year. ;-) 

Kind regards Nicholas Herriot

**Comment by LaszloLango** [comment]
@nherriot just copy the quoted text to the end of the commit message and squash the commits into one commit.

`IoT.js-DCO-1.0-Signed-off-by: nicholas.herriot nicholas.herriot@gmail.com`
and NOT
`Signed-off-by: nicholas.herriot nicholas.herriot@gmail.com`.

For more details please check the related documentation:
https://github.com/Samsung/iotjs/blob/master/docs/devs/IoT.js-Developer's-Certificate-of-Origin-1.0.md

**Comment by yichoi** [comment]
I will keep this closing until you guys understand developments guides of IoT.js

**Pull request closed without merging**
