### PR TITLE
Initialization of in source documentation.

### PR DESCRIPTION
**Pull request by lemmaa**
Change URL links to direct local *.md file.

IoT.js-DCO-1.0-Signed-off-by: Sung-Jae Lee sjlee@mail.com

### CODE REVIEW

**Comment by wateret** [comment]
LGTM

**Comment by ILyoan** [comment]
@lemmaa 
LGTM in general, but I wonder if we need to have  'docs/GPIO-API-candidate.md' as it already had been merged into master. it is no longer a candidate we can see the API specification from https://github.com/Samsung/iotjs/wiki/IoT.js-API:-GPIO

**Comment by lemmaa** [comment]
@ILyoan I have updated the PR. :)

remove 
GPIO-API-candidate.md

add
IoT.js-API-Assert.md
IoT.js-API-Buffer.md
IoT.js-API-DNS.md
IoT.js-API-Events.md
IoT.js-API-File-System.md
IoT.js-API-GPIO.md
IoT.js-API-HTTP.md
IoT.js-API-Module.md
IoT.js-API-Net.md
IoT.js-API-Process.md
IoT.js-API-Stream.md
IoT.js-API-Timers.md

**Comment by ILyoan** [comment]
@lemmaa Looks good to me

**Pull request merged**
