### PR TITLE
Remove 'iotjs_jhelper_call' function from bindings

### PR DESCRIPTION
**Pull request by LaszloLango**
IoT.js-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
The patch reduces the binary size by 1 Kbyte.

**Comment by zherczeg** [comment]
Nice!

**Comment by daeyeon** [comment]
I'm worried the side effect for modules not verified on Travis. How about breaking these into smaller patches? e.g) verified group and not-verified one

**Comment by LaszloLango** [comment]
If you like this change and this is a good direction then I can divide the patch to smaller ones.

**Comment by daeyeon** [comment]
@LaszloLango We've decided to agree with your idea because of the size benefit. The previous one seems somewhat handier though.

**Pull request closed without merging**
