### PR TITLE
Enable LTO.

### PR DESCRIPTION
**Pull request by bzsolt**
IoT.js-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by egavrin** [comment]
Please add "Related issue: #274" for the commit message.

**Comment by bzsolt** [comment]
I missed that, thanks.

**Comment by egavrin** [comment]
Looks good to me.

PS. I suppose it's better to wait for approve from someone else too.

**Comment by seanshpark** [comment]
Need to test for Nuttx / STM32F4-discovery.

**Comment by chunseoklee** [comment]
During nuttx build, the following msg is shown:

LD: nuttx
/home/twoflower/usr/dev/harmony/nuttx/nuttx/lib/libjerrycore.a: error adding symbols: Bad value
make[1]: *** [nuttx] Error 1

It seems that LTO makes some jerry symbols not readable from nuttx linker. Do someone has any solution ?

**Comment by huxinx** [comment]
I do not have STM32F4-discovery at this moment. For my experience, on x86, with gcc 4.9, just enable jerry_cmake_opt.append('-DENABLE_LTO=ON' is fine. With gcc 4.8, need to send extra flag '-flto' , other introduces link error. What is your gcc version?

**Comment by huxinx** [comment]
Another update maybe necessary,
explicitly use gcc-ar and gcc-ranlib for LTO build when using GCC 4.9.

**Comment by seanshpark** [comment]
@bzsolt , can you check with STM32F4-disco + NuttX ? or If you don't have any target boards, you can  check with compilation only and leave some comments about the results here.
And can you use an option in `build.py` so that we can turn the switch? First we can use `--lto` option to turn it on and when we think it's ok for default then switch it on. If some one want's to turn it off he or she  can use `--no-lto` option to disable it.

**Comment by bzsolt** [comment]
Of course, I've checked it with a board, and I've got the same linking error.

From the GCC's site:
>Link-time optimization does not work well with generation of debugging information. 
Combining -flto with -g is currently experimental and expected to produce unexpected results.

I've try to figure out what is the cause, I've tried to disable the debug options (such as `-g`, `-gdwarf-4`), but it doesn't help, so I haven't found any solution for this error yet.

**Comment by ILyoan** [comment]
@bzsolt Remaking build.py is now ongoing.
You may find the changes in #281.
After the PR landed, we can turn on LTO with `build.py --jerry-lto`.

**Comment by bzsolt** [comment]
The linker still fails.
I've tried the LTO build with different gcc version.
In case of gcc-4.8, I've got the above mentioned error.
With gcc-4.9, the following:
```
LD: nuttx
arm-none-eabi-ld: warning: cannot find entry symbol __start; defaulting to 08000000
stm32_vectors.o: In function `exception_common':
.../nuttx/arch/arm/src/chip/stm32_vectors.S:363: undefined reference to `up_doirq'
stm32_vectors.o: In function `_vectors':
stm32_vectors.S:(.vectors+0x4): undefined reference to `__start'
```

I' ve wanted to keep these symbols in object files with ```extern "C"```, ```__attribute__((used)))```, but the compiler disregarded these attempts.

In further, I think the all-in-one build will be a good substitute for LTO on NuttX.
Please check the details [here](https://github.com/Samsung/jerryscript/issues/626#issuecomment-156475847).

**Pull request closed without merging**
