### PR TITLE
Update the document about execution option

### PR DESCRIPTION
**Pull request by hs0225**
Added description about execution options. https://github.com/Samsung/iotjs/issues/391

IoT.js-DCO-1.0-Signed-off-by: Hosung Kim hs852.kim@samsung.com

### CODE REVIEW

**Comment by yichoi** [comment]
It would be better to separate build options and execution options.

**Comment by hs0225** [comment]
@yichoi Ok, that sounds good.

**Comment by hs0225** [comment]
@yichoi I modified a document to reflect your opinion. And corrected any mistakes.

**Comment by LaszloLango** [comment]
LGTM

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
