### PR TITLE
Fix the style of the example snippets in the API documentations.

### PR DESCRIPTION
**Pull request by LaszloLango**
IoT.js-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by daeyeon** [comment]
Can you kindly add more fixes for Buffer.md? It's landed without removing the section titles such as Class Methods, Prototype Methods, Properties, and so on.

**Comment by LaszloLango** [comment]
@daeyeon sure I'll check it and fix what I found.

**Comment by zherczeg** [comment]
I worked on the buffer.md and will update it.

**Comment by LaszloLango** [comment]
@daeyeon @zherczeg I've done it in this PR. Plaese check.

**Pull request merged**
