### PR TITLE
Refactoring Gpio

### PR DESCRIPTION
**Pull request by chunseoklee**
1. unified GpioCbWrap
2. unified GpioCbData
3. unified After callback instead of AfterXXX

IoT.js-DCO-1.0-Signed-off-by: Chunseok Lee chunseok.lee@samsung.com

### CODE REVIEW

**Comment by ILyoan** [comment]
It looks like `GpioCbWrap` is only for GPIO module. Why we have separate 'iotjs_gpiocbwrap.h' file? Is there a problem on having `GpioCbWrap` in 'iotjs_module_gpioctl.h` ?

**Comment by ILyoan** [comment]
If I'm rigiht, `GpioCbWrap` is aggregating `GpioCbData` as `GpioCbWrap` allocates an instance of `GpioCbData` on its constructor and release it on its  destructor. In this case, we can just let `GpioCbWrap` own  `GpioCbData` as member value not by pointer. Furthermore, we might even not need to have `GpioCbData` class by just make `GpioCbWrap` have properties of it.

**Comment by ILyoan** [comment]
Also I think `GpioCbWrap` could be a concrete class of `ReqWrap`. and we can consider renaming it to `GpioReqWrap`.

**Comment by chunseoklee** [comment]
1. iotjs_gpiocbwrap.h/cpp were removed. ```GpioCbWrap``` and ```GpioCbData``` moved to iotjs_module_gpioctl.h
2. ```GpioCbWrap``` has ```GpioCbData``` as member variable, not as pointer now. 

I think  ```GpioCbData``` should be remained since it should be passed to ```gpioctrl->XXX(data, After)``` function as an args.

**Comment by ILyoan** [comment]
@chunseoklee Let's get this merged at this level to go forward.

**Comment by chunseoklee** [comment]
Merged

**Pull request closed without merging**
