### PR TITLE
TizenRT support for UART

### PR DESCRIPTION
**Pull request by kolipka**
IoT.js-DCO-1.0-Signed-off-by: Konrad Lipner k.lipner@samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
The new file looks the same as the NuttX support of UART. Is there any difference? I think we should revise the platform folder to reduce the code duplications in the near future.

**Comment by kolipka** [comment]
no, it is exactly the same. 
If I may, I would also suggest changing file naming rules, since adding folder name as a prefix (the same with os name suffix) seems to hide meaningful part of file name. The same with mixing _ with -

**Comment by yichoi** [comment]
@kolipka please rebase it to the master

**Comment by yichoi** [comment]
@kolipka BTW, please add your test result on real target like https://samsung.github.io/iotjs-test-results/
I hope you wil make a site like this for TizenRT & Tizen  sooner or later

**Pull request closed without merging**
