### PR TITLE
TizenRT support for UART

### PR DESCRIPTION
**Pull request by kolipka**
IoT.js-DCO-1.0-Signed-off-by: Konrad Lipner k.lipner@samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
Why did you closed the previous PR?

**Comment by yichoi** [comment]
I wonder why you did, too

**Comment by kolipka** [comment]
@LaszloLango I messed up git repo and removed branch. My mistake.

**Comment by LaszloLango** [comment]
Previous conversation: #925

I just realized there was a question I haven't answered yet. IMHO we can land the PR without any modification and open an issue for further discussion about the structure of the platform folder. LGTM

**Pull request merged**
