### PR TITLE
Update JerryScript submodule

### PR DESCRIPTION
**Pull request by robertsipka**
This update contains jerry debugger improvements and several bug fixes.

### CODE REVIEW

**Comment by zherczeg** [comment]
I thnik the jerry-api.h includes should be changed to jerryscript.h.

**Comment by yichoi** [comment]
Travis failed. please check the coding rules with ``check_tidy.py``

**Comment by yichoi** [comment]
LGTM

**Comment by hs0225** [comment]
LGTM

**Pull request merged**
