### PR TITLE
[WIP] Use correct headers when building jerry and libtuv

### PR DESCRIPTION
**Pull request by pmarcinkiew**
This patch fixes previous issue with build system not using
correct TizenRT path, thus creating completely broken build.

IoT.js-DCO-1.0-Signed-off-by: Jaroslaw Pelczar j.pelczar@samsung.com

### CODE REVIEW

**Comment by pmarcinkiew** [comment]
Two PRs for JerryScript were created to remove conversion warnings detected by Travis for Nuttx headers.

https://github.com/jerryscript-project/jerryscript/pull/2005
https://github.com/jerryscript-project/jerryscript/pull/2007

**Comment by pmarcinkiew** [comment]
This PR was created to fix test test_iotjs_syntax_error for TizenRT:

https://github.com/Samsung/iotjs/blob/master/test/run_fail/test_iotjs_syntax_error.js

An error handling is based on setjmp, longjmp which are not correctly compiled because IoT.js fails to pass valid header configuration to libtuv and jerryscript.

**Comment by pmarcinkiew** [comment]
It will be mandatory after this PR will be enabled for us:

https://github.com/Samsung/TizenRT/pull/462

**Comment by pmarcinkiew** [comment]
This is fix for issue: https://github.com/Samsung/iotjs/issues/1157

**Comment by yichoi** [comment]
I am closing since this patch has not passed travis for a long time. That is I assume that you don't have enough time or intention to resolve this situation to meet one of our major milestone the second internal release. If the priory of this patch would be changed. I will relocate proper person to handle this.

**Pull request closed without merging**
