### PR TITLE
module: support node_modules and fix index loading

### PR DESCRIPTION
**Pull request by yorkie**
Add the following 2 features:

- load modules from the `node_modules` directories
- load this kind of module `foobar/index.js` by `./foobar`

### CODE REVIEW

**Comment by glistening** [comment]
@yorkie We have discussed several times about this policy. Please see https://github.com/Samsung/iotjs/pull/1305. We decided not to load `node_modules` by default.

**Comment by yorkie** [comment]
> We decided not to load node_modules by default.

So do we have a plugin way to add the directories to load modules?

BTW, how about the another bugfix in this PR, when we have a directory: 

```
|-foo
   |- index.js
```

Then the following requires is working on Node.js:

```js
require('./foo');
```

**Comment by glistening** [comment]
@yorkie Let's handle the two items separately. 

1. Providing additional module load directory
We have discussed internally several times. We need to talk about it more on separate issue

2. search index.js under specified directory by default
I think we could add this feature. But I would like to other's opinions.

**Comment by yorkie** [comment]
Okay, I will submit separately later :)

**Pull request closed without merging**
