### PR TITLE
Specify nuttx tag to improve maintenance

### PR DESCRIPTION
**Pull request by hs0225**
The latest version of nuttx does not guarantee the build and execution of iotjs. Therefore, we need to specify a verified version of nuttx. 
I confirmed that all tests have been passed in the tag I specified.

IoT.js-DCO-1.0-Signed-off-by: Hosung Kim hs852.kim@samsung.com

### CODE REVIEW

**Comment by yichoi** [comment]
I think you forgot to specify which version of nuttx is supported on document

**Comment by hs0225** [comment]
@yichoi I updated the document with your opinion. Please review again.

**Comment by yichoi** [comment]
LGTM

**Comment by chokobole** [comment]
LGTM

**Pull request merged**
