### PR TITLE
External magic string list should be generated automatically

### PR DESCRIPTION
**Pull request by yichoi**
Related issue: Samsung/jerryscript#922 Samsung/iotjs#92

### CODE REVIEW

**Comment by zherczeg** [comment]
We have plans to implement a similar feature in JerryScript (external string generation during snapshot creation). Is this urgent to go in, or can it wait?

**Comment by yichoi** [comment]
I also think it would be much better if jerryscript had this feature internally.

But please consider below requirements:
- IoT.js has multiple js files to generate snapshot
- Each snapshot can be loaded & executed separately
- Each js files may have duplicated strings

And my experimental result: IoT.js binary size gets much bigger with external magic string enabled. I think it's due to duplication of strings: snapshots have string literals inside, and external magic string array also have almost the same set of string literals. I think it would be great if we can remove this duplication. (maybe only for XIP-enabled devices?)

**Comment by zherczeg** [comment]
In theory I would concatenate all js file, and run the external string generator once. This would enable to remove duplications.

**Comment by zherczeg** [comment]
There was a time, when snapshots contained external string references. However, if the external string table changes, the snapshot is loaded incorrectly, and there is no way to test it during loading time. So this feature has been removed.

**Comment by yichoi** [comment]
@zherczeg, could you please share your schedule about when to implement this feature in jerryscript?

**Comment by zherczeg** [comment]
It is among the next steps but not yet scheduled. If you wish we can land this and change things after that task is done.

**Comment by yichoi** [comment]
Thank you. Let's land first then remove after your implementation end.

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
