### PR TITLE
Typo Error Correction in Comment line

### PR DESCRIPTION
**Pull request by gudbooy**
just typographical error correction in comment line :)

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Comment by akiss77** [comment]
@gudbooy The commit message misses the IoT.js-DCO-1.0-Signed-off-by line. Please refer to https://github.com/Samsung/iotjs/wiki/IoT.js-Developer's-Certificate-of-Origin-1.0 . Please add that to your commit and rebase it to current master as well (both are needed for getting your PR merged).

**Comment by akiss77** [comment]
@gudbooy We'd be more than happy to accept your PR, it just needs some minor adjustments (see above). Could you please / do you plan to edit and update your patch?

**Comment by gudbooy** [comment]
@LaszloLango I changed the commit message and check there are no conflicts with current master branch.

**Comment by akosthekiss** [comment]
@gudbooy It took a while to get this landed, sorry about it. Now it just happened. Thanks for the patch.

(One note: for upcoming pull requests, please make sure that you create a separate branch for them and open the PR from that branch, not from your master.)

**Pull request merged**
