### PR TITLE
Improve HTTPS module curl write callback

### PR DESCRIPTION
**Pull request by galpeter**
When the curl called the write callback the data
was copied into a JerryScript array by index
(iotjs_jval_create_byte_array) which can be inefficient
for big data.

By switching to an IoT.JS interal buffer we can speed up
the callback operation.

IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by galpeter** [comment]
resolves issue: #1294

**Comment by Ash200012** [comment]
When will this be merged into master?

**Comment by yichoi** [comment]
LGTM

**Comment by yichoi** [comment]
@Ash200012 merged now! :)

**Comment by Ash200012** [comment]
thank you so much guys!

**Pull request merged**
