### PR TITLE
Update TLS certificates to extend their lifetime

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

**Comment by DanielBallaSZTE** [comment]
@zherczeg 365 days

**Comment by yichoi** [comment]
How about writing a document a certificate with openCA and others ?

**Comment by DanielBallaSZTE** [comment]
@yichoi You can find those in the `test_tls_ca.js` file, in the comment section.

**Comment by yichoi** [comment]
@DanielBallaSZTE OK. 'test_tls_ca.js' is fine for me. Somewhat not fully satisfied with me since some tests related to TLS would be failed after next year which you have prolonged

**Comment by DanielBallaSZTE** [comment]
@yichoi You are right. But in my opinion it is very easy to renew those files, doesn't even take about 5 minutes, following the steps written in the test file. :)

**Comment by zherczeg** [comment]
What about extending it to 10 years? These are just test files.

**Comment by DanielBallaSZTE** [comment]
@zherczeg Yeah that's another possibility, I could do it as well.

**Comment by DanielBallaSZTE** [comment]
@zherczeg @yichoi I have updated the certs to be valid for 10 more years.

**Comment by yichoi** [comment]
LGTM.
You guys think our project would be perished in 10 years :)

**Pull request merged**
