### PR TITLE
Update the document about "IoT.js Package".

### PR DESCRIPTION
**Pull request by nova0821**
Added description that ipm server is not working currently.

IoT.js-DCO-1.0-Signed-off-by: Jaechul Yang jc08.yang@samsung.com

### CODE REVIEW

**Comment by nova0821** [comment]
This is about https://github.com/Samsung/iotjs/issues/386.

After merging this commit, need to update WiKi page with new title. (https://github.com/Samsung/iotjs/wiki/IoT.js-Package)

**Comment by yichoi** [comment]
Please add a patch to rename docs/IoT.js-package.md to docs/IoT.js-Package-(outdated).md
I will rename wiki page with this updated document.

**Comment by nova0821** [comment]
@yichoi, File name is changed.

**Comment by yichoi** [comment]
LGTM

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
