### PR TITLE
http.get added

### PR DESCRIPTION
**Pull request by chunseoklee**
IoT.js-DCO-1.0-Signed-off-by: Chunseok Lee chunseok.lee@samsung.com

### CODE REVIEW

**Comment by wateret** [comment]
What happens when we call *http.get()* with argument *option.method = 'POST'*
The request will be sent as GET or POST?

**Comment by wateret** [comment]
LGTM

**Comment by chunseoklee** [comment]
@wateret In node, request is sent as 'POST' without checking. There might be some options : ex. throw exception if 'POST' method is passed on http.get call.

**Comment by chunseoklee** [comment]
Merged

**Pull request closed without merging**
