### PR TITLE
Simplify C part of the http-parser module

### PR DESCRIPTION
**Pull request by galpeter**
* Removed a IOTJS_VALIDATED_STRUCT_METHOD macro usage.
* Extracted Resume/Pause common code parts.
* Extracted parse error generation code part to a single method.

Reduces binary code size a bit.

IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by glistening** [comment]
@galpeter `IOTJS_VALIDATE_STRUCT_METHOD` is used almost all modules sources. Could you remove `IOTJS_VALIDATED_STRUCT_METHOD` changes from this PR? Basically we would like to keep the validation check although it reduces readability.

**Comment by glistening** [comment]
@galpeter Did you run related unit tests on NuttX and RPI also?

**Comment by yichoi** [comment]
LGTM if test succeed

**Comment by robertsipka** [comment]
I've tested on NuttX and RPi, the tests were passed except the `test_net_http_request_response.js` test which currently fails on master as well.

**Pull request merged**
