### PR TITLE
Set Coverity-Scan

### PR DESCRIPTION
**Pull request by daeyeon**
This commit gets Coverity-Scan run whenever master branch is updated.

IoT.js-DCO-1.0-Signed-off-by: Daeyeon Jeong daeyeon.jeong@samsung.com

### CODE REVIEW

**Comment by robertsipka** [comment]
I'm not sure that this secure (COVERITY_SCAN_TOKEN) encrypted variable should work. It was encrypted and encoded using the private Project token from Coverity Scan project settings. As I see [here](https://scan.coverity.com/projects/daeyeon-iotjs), it points to your forked repository.
Encryption and decryption keys are tied to the repository. If you fork a project and add it to Travis CI, it will not access to the encrypted variables.

**Comment by daeyeon** [comment]
Thank you for your concern. This is actually a different commit from the one you mentioned with the encrypted value for my repository. This uses the different one which is pointing to [Samsung/iotjs](https://scan.coverity.com/projects/samsung-iotjs) instead.

**Comment by robertsipka** [comment]
Thanks, I can't found that, I can't able to  access this page.  This would be a private measurement site? 
If not, could you please also place the project's Coverity Scan badge in the README file?

**Comment by daeyeon** [comment]
Agree with you. I just pushed another commit including the badge. The page would be viewable for all users.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
