### PR TITLE
Cover a few missing functions

### PR DESCRIPTION
**Pull request by DanielBallaSZTE**
Covering some of the missing public functions, migrating parallel/test-net-keepalive.js.

IoT.js-DCO-1.0-Signed-off-by: Daniel Balla dballa@inf.u-szeged.hu

### CODE REVIEW

**Comment by DanielBallaSZTE** [comment]
The test `test-net-bind-twice.js` seems to fail, somehow I was thinking it was my test that was failing, as the test system says it's failing, however it doesn't, the test before it fails.

**Comment by DanielBallaSZTE** [comment]
As both @robertsipka and my tests are failing I assume that it is caused by the previous `test-net-bind-twice.js` not closing properly, (or in time) as both of our tests are net tests, and both cause that test to fail. I think a timeout in testsets.json would solve the issue, or putting it in the test itself would solve it either.

**Comment by yichoi** [comment]
@DanielBallaSZTE  please rebase it to the master

**Comment by DanielBallaSZTE** [comment]
Rebased to master

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
