### PR TITLE
Fix http-parser submodule commit hash

### PR DESCRIPTION
**Pull request by galpeter**
After cloning out the iotjs repository, the hash 7e1178d99af814a208c6f8b6b604d58f96dcd3b0 is not available. The new hash seems to be contain the same modifications.

IoT.js-DCO-1.0-Signed-off-by: Peter Gal pgal.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by galpeter** [comment]
Without the patch I'm getting the following error when building:
```
Unable to checkout '7e1178d99af814a208c6f8b6b604d58f96dcd3b0' in submodule path 'deps/http-parser'
```

**Comment by chunseoklee** [comment]
@galpeter I made a mistake that 7e1178d99af814a208c6f8b6b604d58f96dcd3b0 is removed from http-parser repo by ```push --force```. Sorry for that. I will send a new PR to update new http-parser commit.

**Comment by chunseoklee** [comment]
#251 will fix the issue.

**Comment by chunseoklee** [comment]
closed by #251 ladend

**Comment by galpeter** [comment]
@chunseoklee I'm a bit curious why do we created another PR with the same fix as this PR? Was there something wrong with my fix?

**Comment by chunseoklee** [comment]
@galpeter I am very sorry that I make the same PR as yours. I thought that your PR checkouted to previous commit(6f883bd2c874d483ec43e25256fbfdc105ccad6b).
Again, I am very sorry for this situation.

**Pull request closed without merging**
