### PR TITLE
Improve the test coverage.

### PR DESCRIPTION
**Pull request by knightburton**
Add a new test file for dns lookup.

IoT.js-DCO-1.0-Signed-off-by: Imre Kiss kissi.szeged@partner.samsung.com

### CODE REVIEW

**Comment by glistening** [comment]
Currently valgrind memory leak test fails. Thank you for finding the memory leak! Could you fix the dns memory leak? If so, could you kindly include the fix in this PR? If not, please modify testsets.json to skip this dns test on linux so that we can merge this fix by making travis happy.

**Comment by yichoi** [comment]
Please make this PR to one single commit and fix memory leak found by your new tests.

**Comment by knightburton** [comment]
Sure, i'm working on it.

**Comment by knightburton** [comment]
Updated.
Note: On travis no IPv6 support in Trusty VM.
Currently we can not test the dns lookup with IPv6 family option.

**Comment by hs0225** [comment]
Please check coding style guideline. 

```js
function() {
}
```
```js
assert.equal(err, null);
```

**Comment by knightburton** [comment]
Sorry about that. It's updated.

**Pull request merged**
