### PR TITLE
Initial commit for dns module

### PR DESCRIPTION
**Pull request by wateret**
Created dns module.

APIs added
* dns.lookup() - for #205

### CODE REVIEW

**Comment by chunseoklee** [comment]
@wateret It it difficult to add test file for this feature ?

**Comment by wateret** [comment]
Yes it is difficult to add tests.
Even testing with 'localhost', ip addresses other than '127.0.0.1' could be the answers.
I also found **gethostip** command in Linux which prints an ip address for a hostname but Mac OS doesn't have it.

**Comment by ILyoan** [comment]
@wateret Looks like js file is missing.

**Comment by wateret** [comment]
Just added it.

**Comment by wateret** [comment]
Added  a commit.
Now argument *host* in *socket.connect()* is resolved with *dns.lookup()*. It emits 'lookup' event as well.

@chunseoklee With this commit, I was able to make a test case for dns module which creates a server and connects to it with hostname 'localhost' instead of '127.0.0.1

**Comment by wateret** [comment]
Updated the test file to test 'lookup' event as well.

**Comment by ILyoan** [comment]
+1

**Comment by chunseoklee** [comment]
LGTM

**Pull request merged**
