### PR TITLE
Replace isUndefined() calls

### PR DESCRIPTION
**Pull request by tkeri**
Deleted isUndefined(arg) function calls from
JavaScript sources and replaced these with JavaScript
comparison operator.

IoT.js-DCO-1.0-Signed-off-by: Tamas Keri tkeri@inf.u-szeged.hu

### CODE REVIEW

**Comment by tkeri** [comment]
When I measured these tests the result was hectic. So, I try to do something with the big standard derivation. The reason of this big stddev is that we didn't have any influence when the GC will be called, and when the network driver answer to our query. So, my approach was to limit the maximum heap memory, and the expectation was that the stddev will be better in way. As you can see in the table, limiting the heap memory can lead to have a much more consequent results. Of course this method didn't solve any of the original problem, but the measurement and the results will be more consistent.

**Comment by LaszloLango** [comment]
> As you can see in the table

What table?

**Comment by tkeri** [comment]
**Tester: freya, build: release arm-rpi2 7c886d1**
===================
| testfile                                   | total       | peak        | max rel stdev  |
|--------------------------------------------|-------------|-------------|----------------|
|                                            | diff / byte | diff / byte |        %       |
||||
| run_pass/test_net_7.js                     |             |             ||
| Jerry Heapsize: 256                        | +197        | +383        |    9.45        |
| Jerry Heapsize: 87                         | -494        | -23884      |    10.45       |
| run_pass/test_net_http_request_response.js |             |             ||
| Jerry Heapsize: 256                        | +37         | -7133       |    5.24        |
| Jerry Heapsize:  53                        | -514        | +157        |    0.64        |
| run_pass/test_net_httpserver.js            |             |             ||
| Jerry Heapsize: 256                        | -3          | +7913       |    6.13        |
| Jerry Heapsize:   47                       | +314        | -106        |    0.17        |
| run_pass/test_net_http_status_codes.js     |             |             ||
| Jerry Heapsize: 256                        | +59         | -837        |   7.41         |
| Jerry Heapsize:  59                        | +41504      | -99         |   15.68        |

**NOTE:** The '+' means memory saving in bytes.

**Comment by glistening** [comment]
@tkeri Memory reduction is important on lightweight device and OS. So I focused on numbers in arm-rpi2 + small jerry heapsize. As my understanding, the peak memory increased in this case, although stddev is smaller. Is it right?

**Comment by tkeri** [comment]
@glistening Yes, it is, but this test files are hectic. So, the other test files show memory saving with normal stddev + normal jerry heapsize (256). I think these test files are relevant. For example,

**Tester: freya, build: release arm-rpi2 7c886d1**
===================
| testfile                                   | total       | peak        | max rel stdev  |
|--------------------------------------------|-------------|-------------|----------------|
|                                            | diff / byte | diff / byte |        %       |
||||
| run_pass/test_dgram_broadcast.js           |             |             ||
| Jerry Heapsize: 256                        | +21         | +13         |    0        |
| run_pass/test_net_4.js                     |             |             ||
| Jerry Heapsize: 256                        | +21         | +245        |    0        |
| run_pass/test_fs_open_read.js              |             |             ||
| Jerry Heapsize: 256                        | +29         | +141        |    0        |
| run_pass/test_uart.js                      |             |             ||
| Jerry Heapsize: 256                        | +21         | +13         |    0        |
| run_pass/test_fs_mkdir_rmdir.js            |             |             ||
| Jerry Heapsize: 256                        | +61         | +13         |    0        |
| run_pass/test_net_11.js                    |             |             ||
| Jerry Heapsize: 256                        | +37         | +13         |    0        |
| run_pass/test_net_10.js                    |             |             ||
| Jerry Heapsize: 256                        | +77         | +133        |    0        |
| run_pass/test_i2c.js                       |             |             ||
| Jerry Heapsize: 256                        | +21         | +13         |    0        |
| run_pass/test_module_cache.js              |             |             ||
| Jerry Heapsize: 256                        | +29         | +13         |    0        |

**NOTE:** The '+' means memory saving in bytes.

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
