### PR TITLE
Fix readdir testcase failure

### PR DESCRIPTION
**Pull request by glistening**
I did not push some directories for readdir test.
My git add command was ignored since git does not permit
committing empty directory.
I add dummy files in previously empty directories.
    
IoT.js-DCO-1.0-Signed-off-by: Sanggyu Lee sg5.lee@samsung.com

### CODE REVIEW

**Comment by chokobole** [comment]
@glistening  How about trying one of these suggestions either `touch .gitkeep` inside the empty diretory or add `!resources` in .gitignore?

**Comment by yichoi** [comment]
+1 on `.gitkeep`

**Comment by glistening** [comment]
Originally I want to describe the reason of seemingly dummy file explicitly and transparently. Perhaps I will forgot the intent after some time passes. However, at least two committers seem to want to make the file hidden and make name short. Also, I agree this change may be enough. Thank you for review.

**Comment by zherczeg** [comment]
LGTM

**Pull request merged**
