### PR TITLE
Optimize localhost lookups for Nuttx/TizenRT

### PR DESCRIPTION
**Pull request by tosyu**
This optimization helps when running dgram module code (and tests) on TizenRT/nuttx as "localhost" is not resolved on those platforms to IP address.

### CODE REVIEW

**Comment by daeyeon** [comment]
Is this a temporary workaround to conquer the tests in fail? What if a local dns lookup like `/etc/hosts` is intentionally changed? I'm not sure that we could ignore such a case.

**Comment by tosyu** [comment]
@daeyeon this is just for Nuttx/TizenRT.

This solution is the same like in dns module:

https://github.com/Samsung/iotjs/blob/master/src/modules/iotjs_module_dns.c#L146 from PR #491 done by Wonyong Kim

**Comment by pmarcinkiew** [comment]
In my opinion we should implement consistent DNS lookup. If there is additional logic for loopback in DNS, why it is wrong in UDP?

**Comment by zherczeg** [comment]
This should be a workaround, and should be improved later. But could go in now.

**Comment by daeyeon** [comment]
@pmarcinkiew If so, why not removing the logic in DNS instead? 

I just want to know why we should accept this workaround now. Is there any tangible benefit we can have for now? e.g) a certain unit test passes.

**Comment by daeyeon** [comment]
I'd like to close this because, as of no response, it seems not urgent to accept this workaround.

**Pull request closed without merging**
