### PR TITLE
jerry: Propagate ENABLE_STATIC_LINK cmake flags

### PR DESCRIPTION
**Pull request by rzr**
This can be helful for packagers,
who prefer to turn this variable off to use use system's libc.

Currently it will only be used for iotjs code,
but kept static in jerryscript module, this is not wanted.

IoT.js-DCO-1.0-Signed-off-by: Philippe Coval philippe.coval@osg.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
typo in commit message: `helpful`

**Comment by galpeter** [comment]
There are two jerry targets in the cmake file. You have modified the host jerry build which is only for snapshot generation during build. The other jerry build is the target jerry which will be used by the iotjs. Is this what you wanted?

Also I think there is a typo in the commit message: `... use use ...`

**Comment by yichoi** [comment]
@rzr any further comments?

**Comment by daeyeon** [comment]
Closed because of no further response.

**Pull request closed without merging**
