### PR TITLE
Update JerryScript submodule

### PR DESCRIPTION
**Pull request by rtakacs**
According to #602 I've created a patch to update JerryScript.

### CODE REVIEW

**Comment by LaszloLango** [comment]
@rtakacs after (https://github.com/jerryscript-project/jerryscript/commit/638b75313595461cc0caaa02cc97a708421c6920) it should work. Please update to the latest JerryScript.

**Comment by zherczeg** [comment]
Please wait for #1574 in jerryscript before landing this.

**Comment by rtakacs** [comment]
@zherczeg : I've updated jerry to **32674ff** [Documentation update (#1573)]

**Comment by LaszloLango** [comment]
Let's suspend this update until we investigate it's effects on memory consumption.

**Comment by LaszloLango** [comment]
False alarm. Tested the PR and there are no issues.

**Pull request merged**
