### PR TITLE
Nuttx tests in romfs

### PR DESCRIPTION
**Pull request by tadziopazur**
Provides read-only contents of iotjs/test (from repository) to target device at /etc/test.

### CODE REVIEW

**Comment by yichoi** [comment]
@tadziopazur Please make one single commit per PR. and you are supposed to check the result of travis after you commit.

**Comment by tadziopazur** [comment]
Single commit -- does that mean I should compress https://github.com/Samsung/iotjs/pull/1138 and this one into a single commit?
That one has its own PR with some ongoing discussion.
This one is basically a follow-up.
My approach is: 
1. have nuttx build that works (#1138)
2. add tests to it (this one)
3+ add other things (future ones)

Regarding why Travis does not like the mkromfs script, I am checking it.
Precommit did work on my machine.

**Comment by daeyeon** [comment]
@tadziopazur I understand your approach, but you need to squash them if it's a logical unit of work and you can't wait for review requests. That's this project's way to get the pain out of managing PRs. If a PR doesn't contain a single commit, it will be hard to collaboratively discuss your code. Different opinions of people could be scattered to your several commits.

**Comment by tadziopazur** [comment]
I see and I agree -- no multiple commits in a single PR.
This PR has a single unique commit.
It also depends on another PR, that should be merged first.
This one has no value, if #1138 is not merged.
It also does not work the other way - #1138 is perfectly fine with this one NOT merged.

If you insist, I can provide it as a single commit though, I'll need to handle rebase anyway.

**Comment by yichoi** [comment]
I landed @haesik 's commit please, rebase it with ```06ca1a9b06405db32bdf06f734d828b2d8ae2cdf```

**Comment by yichoi** [comment]
There must be common routines between #1140 and #1183. Please take into account of it.

**Comment by hs0225** [comment]
Please make one commit and put it up again.

**Pull request closed without merging**
