### PR TITLE
Replace some type checker calls

### PR DESCRIPTION
**Pull request by tkeri**
Deleted isNumber(arg) function calls from
JavaScript sources and replaced these with JavaScript
comparison operator.

Deleted isBoolean(arg) function calls from
JavaScript sources and replaced these with JavaScript
comparison operator.

Deleted isString(arg) function calls from
JavaScript sources and replaced these with JavaScript
comparison operator.

Deleted isFunction(arg) function calls from
JavaScript sources and replaced these with JavaScript
comparison operator.

IoT.js-DCO-1.0-Signed-off-by: Tamas Keri tkeri@inf.u-szeged.hu

### CODE REVIEW

**Comment by yichoi** [comment]
http://travis-ci.org/Samsung/iotjs/jobs/270112838
Please make cody tidy

**Comment by tkeri** [comment]
Done

**Comment by hs0225** [comment]
@tkeri I think, these type checkers are easy to mistake unlike checking `null` and `undefined`. In particular, `Object` should check `arg !== null && typeof arg === 'object'`. It seems inconsistent to remove utility function except `isObject`.

**Comment by yichoi** [comment]
@tkeri rebase please

**Comment by yichoi** [comment]
@tkeri you are supposed to remove merge commit

**Comment by hs0225** [comment]
This PR seems to require further discussion. If you want to your PR, please register the issue. Once I close this PR. Thank you.

**Pull request closed without merging**
