### PR TITLE
Fix i2c.writeBytes() and remove the duplicate of I2C_SMBUS_BLOCK_MAX

### PR DESCRIPTION
**Pull request by bzsolt**
IoT.js-DCO-1.0-Signed-off-by: Zsolt Borbély zsborbely.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by bzsolt** [comment]
CI fails due to missing `zlib` archive, fixed in https://github.com/Samsung/iotjs/pull/599

**Comment by nova0821** [comment]
@bzsolt  Also, #599 is merged to master branch, you can rebase it.

**Comment by bzsolt** [comment]
@nova0821 This test passes on my environment, but there is something wrong with `i2c.stream`,
because when I allow `test_i2c.js` to run, the subsequent `test_module_cache.js` fails, when `stream` function called.

**Comment by nova0821** [comment]
@bzsolt I'll test it in my test environment and if there is an issue, I'll fix it with another PR. 
Thanks to report it.

**Pull request merged**
